package com.nar.bimito

object Versions {
    const val daggerHiltLifeCycle = "1.0.0-alpha03"
    const val daggerHiltCompiler ="2.31.1-alpha"
    const val daggerHilt = "2.31.1-alpha"
    const val activity = "1.2.2"
    const val arrow = "0.10.4"
//    const val gradle = "4.0.1"
    const val ktlint = "0.37.2"
    const val kotlin = "1.3.72"
    const val coroutines = "1.3.3"
//    const val gradleVersions = "1.3.70"
    const val arch = "2.2.0"
    const val archTest = "2.1.0"
    const val material = "1.2.0-alpha03"
    const val constraintLayout = "1.1.3"
    const val room = "2.2.5"
    const val dagger = "2.25.4"
    const val okHttp = "4.9.0"
    const val gson = "2.8.6"
    const val retrofit = "2.7.1"
    const val stetho = "1.5.1"
    const val glide = "4.11.0"
    const val junit = "4.12"
    const val testRunner = "1.2.0"
    const val espresso = "3.2.0"
    const val mockitoKotlin = "1.6.0"
    const val navigationComponent = "2.3.0"
    const val fragment = "1.2.5"
    const val mapStructVersion = "1.3.1.Final"
    const val KotlinMapStructVersion = "1.3.1.1"
    const val javaxInjectVersion = "1"
    const val moshi = "2.4.0"
    const val daggerHiltKotlin = "1.0.0-beta01"
    const val multiDex = "2.0.1"



}
